imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            channels: ['!event', '!doctrine']
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']
bazinga_faker:
    orm: doctrine
    entities:
        ApiBundle\Entity\Agence:
            number: 5
            custom_formatters:
                nom: { method: company,  parameters: null}
                adresse: { method: streetAddress,  parameters: null}
                codepostal: { method: postcode,  parameters: null}
                ville: { method: country,  parameters: null}
                cA: { method: randomFloat,  parameters: [2, 50000, 9999999999]}
        ApiBundle\Entity\Gerant:
            number: 5
            custom_formatters:
                nom: { method: lastName,  parameters: null}
                prenom: { method: firstName,  parameters: null}
                email: { method: email,  parameters: null}
                password: { method: password,  parameters: null}
