api_gerant:
    resource: "@ApiBundle/Resources/config/routing/routing_gerant.yml"
    prefix:   /gerant

api_vehicule:
    resource: "@ApiBundle/Resources/config/routing/routing_vehicule.yml"
    prefix:   /vehicule

api_client:
    resource: "@ApiBundle/Resources/config/routing/routing_client.yml"
    prefix:   /client

api_location:
    resource: "@ApiBundle/Resources/config/routing/routing_location.yml"
    prefix:   /location