<?php

namespace ApiBundle\Repository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByAgence($idAgence) {
        $query = $this->createQueryBuilder('l')
                    ->leftJoin('l.client', 'c')
                    ->leftJoin('l.vehicule', 'v')
                    ->addSelect('c')
                    ->addSelect('v')
                    ->where('v.agence = :idAgence')
                    ->setParameter('idAgence', $idAgence) ;
        return $query->getQuery()->getResult() ;

    }
}
