vehicules:
    resource: ApiBundle\Controller\VehiculeController
    type:     rest

get_vehicules:
    path:  /agence/vehicules/{idAgence}
    defaults: { _controller: ApiBundle:Vehicule:getByAgence}
